# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestDST():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testDST(self):
    # Test name: Test DST
    # Step # | name | target | value
    # 1 | open | / | 
    self.driver.get("https://assessment.accelerate-people.co.uk/")
    # 2 | setWindowSize | 1035x689 | 
    self.driver.set_window_size(1035, 689)
    # 3 | click | id=submit | 
    self.driver.find_element(By.ID, "submit").click()
    # 4 | click | linkText=Click to enter this course | 
    self.driver.find_element(By.LINK_TEXT, "Click to enter this course").click()
    # 5 | click | css=#module-7 .instancename | 
    self.driver.find_element(By.CSS_SELECTOR, "#module-7 .instancename").click()
    # 6 | click | id=single_button5fa9b148eb02394 | 
    self.driver.find_element(By.ID, "single_button5fa9b148eb02394").click()
    # 7 | click | id=q11:3_answer0 | 
    self.driver.find_element(By.ID, "q11:3_answer0").click()
    # 8 | click | id=yui_3_17_2_1_1604956555204_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956555204_31").click()
    # 9 | click | id=q11:4_answer1 | 
    self.driver.find_element(By.ID, "q11:4_answer1").click()
    # 10 | click | id=yui_3_17_2_1_1604956559739_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956559739_31").click()
    # 11 | click | id=q11:5_answer3 | 
    self.driver.find_element(By.ID, "q11:5_answer3").click()
    # 12 | click | id=yui_3_17_2_1_1604956563344_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956563344_31").click()
    # 13 | click | id=q11:6_answer2 | 
    self.driver.find_element(By.ID, "q11:6_answer2").click()
    # 14 | click | id=yui_3_17_2_1_1604956566567_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956566567_31").click()
    # 15 | click | id=q11:7_answer2 | 
    self.driver.find_element(By.ID, "q11:7_answer2").click()
    # 16 | click | id=yui_3_17_2_1_1604956569735_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956569735_31").click()
    # 17 | click | id=yui_3_17_2_1_1604956572841_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956572841_121").click()
    # 18 | click | id=yui_3_17_2_1_1604956572841_124 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956572841_124").click()
    # 19 | click | id=q11:8_answer0 | 
    self.driver.find_element(By.ID, "q11:8_answer0").click()
    # 20 | click | id=yui_3_17_2_1_1604956572841_141 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956572841_141").click()
    # 21 | click | id=yui_3_17_2_1_1604956572841_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956572841_31").click()
    # 22 | click | id=yui_3_17_2_1_1604956578561_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956578561_121").click()
    # 23 | click | id=q11:9_answer3 | 
    self.driver.find_element(By.ID, "q11:9_answer3").click()
    # 24 | click | id=yui_3_17_2_1_1604956578561_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956578561_31").click()
    # 25 | click | id=q11:10_answer2 | 
    self.driver.find_element(By.ID, "q11:10_answer2").click()
    # 26 | click | id=yui_3_17_2_1_1604956582359_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956582359_31").click()
    # 27 | click | id=q11:11_answer1 | 
    self.driver.find_element(By.ID, "q11:11_answer1").click()
    # 28 | click | id=yui_3_17_2_1_1604956585200_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956585200_31").click()
    # 29 | click | id=q11:12_answer1 | 
    self.driver.find_element(By.ID, "q11:12_answer1").click()
    # 30 | click | id=yui_3_17_2_1_1604956588393_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956588393_31").click()
    # 31 | click | id=yui_3_17_2_1_1604956591679_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956591679_121").click()
    # 32 | click | id=yui_3_17_2_1_1604956591679_143 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956591679_143").click()
    # 33 | click | id=yui_3_17_2_1_1604956591679_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956591679_31").click()
    # 34 | click | id=q11:14_answer3 | 
    self.driver.find_element(By.ID, "q11:14_answer3").click()
    # 35 | click | id=yui_3_17_2_1_1604956596451_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956596451_31").click()
    # 36 | click | id=yui_3_17_2_1_1604956599499_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956599499_121").click()
    # 37 | click | id=yui_3_17_2_1_1604956599499_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956599499_121").click()
    # 38 | click | id=q11:15_answer3 | 
    self.driver.find_element(By.ID, "q11:15_answer3").click()
    # 39 | click | id=yui_3_17_2_1_1604956599499_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956599499_31").click()
    # 40 | click | id=yui_3_17_2_1_1604956604723_121 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956604723_121").click()
    # 41 | click | id=q11:16_answer3 | 
    self.driver.find_element(By.ID, "q11:16_answer3").click()
    # 42 | click | id=yui_3_17_2_1_1604956604723_31 | 
    self.driver.find_element(By.ID, "yui_3_17_2_1_1604956604723_31").click()
    # 43 | click | id=single_button5fa9b1895353617 | 
    self.driver.find_element(By.ID, "single_button5fa9b1895353617").click()
    # 44 | click | id=id_yuiconfirmyes-yui_3_17_2_2_1604956608894_7 | 
    self.driver.find_element(By.ID, "id_yuiconfirmyes-yui_3_17_2_2_1604956608894_7").click()
  
