# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 09:00:32 2020

@author: andy
"""

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from bs4 import BeautifulSoup
import pandas as pd
import os
import glob
import shutil
import pandas as pd
from pathlib import Path
import re 
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime
import pyperclip
from os import path
from docx import Document



# =============================================================================
# Global varaibles
# =============================================================================


# =============================================================================
# Functions
# =============================================================================
def get_file_path(directory_name,filename):    
    director_path=Path(directory_name)
    full_file_path=director_path / filename
    return full_file_path
    

    
# # =============================================================================
# # Import Data  
# # =============================================================================
data_orginal_file=get_file_path(r'C:\Users\Andy.JIVEDIVE\Accelerate People\Accelerate People - Finance',
                                 "EPA Registrations and Invoices .xlsx")
data_dest_file=(r'.\\',"EPA Registrations and Invoices .xlsx")
copy_path_dest=".\\" + "EPA Registrations and Invoices .xlsx"
copy_path_source=str(data_orginal_file)
timestring=datetime.today().strftime('%Y-%m-%d-%H-%M-%S')
#Check old data is there and rename#
if (os.path.isfile(copy_path_dest)):
    new_name=copy_path_dest+timestring
    shutil.move(copy_path_dest,new_name)    

shutil.copy(copy_path_source,copy_path_dest)

data_EPA_bookings=pd.read_excel(copy_path_dest, sheet_name="EPA Bookings")

data_group=data_EPA_bookings.groupby("Grading Received from IA").count()
fig = plt.figure(figsize=(12,10), dpi=800)
plt.title('Count of P/M/D',fontsize=18) 
plt.xlabel("Grade",fontsize=16)
plt.ylabel("Count",fontsize=16)
plt.xticks(rotation=90)
plt.bar(data_group.index,data_group['ULN'])
fig.savefig("fig2.png")
plt.show()


