# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 09:00:32 2020

@author: andy
"""

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from bs4 import BeautifulSoup
import pandas as pd
import os
import glob
import shutil
import pandas as pd
from pathlib import Path
import re 
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

from os import path
from docx import Document



# =============================================================================
# Global varaibles
# =============================================================================


# =============================================================================
# Functions
# =============================================================================
def get_file_path(directory_name,filename):    
    director_path=Path(directory_name)
    full_file_path=director_path / filename
    return full_file_path
    

    
# # =============================================================================
# # Import Data  
# # =============================================================================


data_orginal_file=get_file_path(r"C:\Users\Andy.JIVEDIVE.000\OneDrive - University of Buckingham\Assignments\Final Project\Python","DST-Test-Matrix-01-item-difficulty.xlsx")

#dataset=pd.read_excel(data_orginal_file, sheet_name="TestData",skiprows=range(1,1))
dataset=pd.read_excel(data_orginal_file, sheet_name="TestData")

#Headers and redundant columns
dataset_cleansed=dataset.iloc[1:,1:]

#Read in next set of answer
set=0
for attempt in dataset_cleansed.iterrows():
    #print("Set={} Row=<{}>".format(attempt,row))
    set+=1
    answers=attempt[1]
    question_no=1
    for answer in answers:
        question_no+=1    
        print("Attempt[{}] Question[{}] Answer={}".format(set,question_no,answer))

#data_group=dataset.groupby("Standard").count()
#plt.bar(data_group.index,data_group['Apprentice ULN'])
# data_group=data_EPA_bookings.groupby("Grading Received from IA").count()
# fig = plt.figure(figsize=(12,10), dpi=800)
# plt.title('Count of P/M/D',fontsize=18) 
# plt.xlabel("Grade",fontsize=16)
# plt.ylabel("Count",fontsize=16)
# plt.xticks(rotation=90)
# plt.bar(data_group.index,data_group['ULN'])
# fig.savefig("fig2.png")
# plt.show()


