# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 09:00:32 2020

@author: andy
"""

# Generated by Selenium IDE

import pandas as pd
from pathlib import Path


# =============================================================================
# Global varaibles
# =============================================================================
question_statistics=pd.DataFrame()
difficult_threshold={"min":0.3,"max":0.9}

# =============================================================================
# Functions
# =============================================================================
def get_file_path(directory_name,filename):    
    director_path=Path(directory_name)
    full_file_path=director_path / filename
    return full_file_path
    

    
# # =============================================================================
# # Import Data  
# # =============================================================================
ace360_filename=get_file_path(r"C:\Users\Andy.JIVEDIVE.000\Accelerate People\Accelerate People - ACE360 Reports","Apps Export.xlsx")



ace360_data_df=pd.read_excel(ace360_filename)


#Find any rows with duplicate ACE360 ID
count=ace360_data_df.groupby('ACE360 ID').count()
number_of_duplicates=len(count[count['Status'] >1])
print("Number of duplicate [ACE360 ID]:{}".format(number_of_duplicates))

#Check for nulls in the standard
standard_null_status=ace360_data_df['Standard'].isnull()
standard_null_count=len(standard_null_status[standard_null_status == True])
print("Number of duplicate [Standard]:{}".format(standard_null_count))

training_provider_null_status=ace360_data_df['Training Provider Name'].isnull()
training_provider_null_count=len(training_provider_null_status[training_provider_null_status == True])
print("Number of duplicate [Training Provider Name]:{}".format(training_provider_null_count))


