# -*- coding: utf-8 -*-
"""
Created on Sun Jan 10 14:35:39 2021

@author: andy
"""
# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from bs4 import BeautifulSoup
import pandas as pd
import os
import glob
import shutil
import pandas as pd
from pathlib import Path
import re 
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime

from os import path
from docx import Document


data_series=[4, 17, 7, 14, 18, 12, 3, 16, 10, 4, 4, 11]
data_series_df=pd.DataFrame(data_series)