# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMoodle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_moodle(self):
    self.driver.get("http://192.168.1.86/moodle/")
    self.driver.set_window_size(1354, 824)
    self.driver.find_element(By.CSS_SELECTOR, ".usermenu").click()
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").send_keys("brownam0")
    self.driver.find_element(By.ID, "password").send_keys("87sZL9*2%0&e")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, "#module-2 .instancename").click()
    self.driver.find_element(By.ID, "single_button5f4656adde08b61").click()
    self.driver.find_element(By.ID, "q3:1_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445235548_30").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445240760_115").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445240760_115").click()
    self.driver.find_element(By.ID, "q3:2_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445240760_31").click()
    self.driver.find_element(By.ID, "q3:3_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445246648_31").click()
    self.driver.find_element(By.ID, "q3:4_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445249977_31").click()
    self.driver.find_element(By.ID, "q3:5_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445253939_31").click()
    self.driver.find_element(By.ID, "q3:6_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445256511_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445259871_115").click()
    self.driver.find_element(By.ID, "q3:7_answer2").click()
    self.driver.find_element(By.ID, "region-main").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445259871_31").click()
    self.driver.find_element(By.ID, "q3:8_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445263752_31").click()
    self.driver.find_element(By.ID, "q3:9_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445266672_31").click()
    self.driver.find_element(By.ID, "q3:10_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445269319_31").click()
    self.driver.find_element(By.ID, "q3:11_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445272533_31").click()
    self.driver.find_element(By.ID, "q3:12_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445274824_31").click()
    self.driver.find_element(By.ID, "q3:13_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445277877_31").click()
    self.driver.find_element(By.ID, "q3:14_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445281477_31").click()
    self.driver.find_element(By.ID, "q3:15_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445284589_31").click()
    self.driver.find_element(By.ID, "q3:16_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445287533_31").click()
    self.driver.find_element(By.ID, "q3:17_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445290701_31").click()
    self.driver.find_element(By.ID, "q3:18_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445293447_31").click()
    self.driver.find_element(By.ID, "q3:19_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445295638_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1598445298967_31").click()
    self.driver.find_element(By.ID, "single_button5f4656f486ffb17").click()
    self.driver.find_element(By.ID, "id_yuiconfirmyes-yui_3_17_2_2_1598445300791_8").click()
  
#apprentice_list=[]

#standards_df=pd.DataFrame(standards)
#dataFolder=Path(r"C:\Users\Andy.JIVEDIVE\Downloads")
#dataFolder=Path(r"C:\Users\Administrator\Downloads")
#portfolio_folder=Path(r"C:\Users\Andy.JIVEDIVE\OneDrive - Accelerate People\Portfolio")



    
#file_list_w=glob.glob("C:\\Users\\Andy.JIVEDIVE\\Downloads\\Summative Portfolio*")
#file_list_w=glob.glob(str(wildcard))
#file_list_w.sort(key=os.path.getmtime, reverse=True)    

# Get the apprentices data from WebDriver    

#start_time = datetime.now()

a=TestMoodle()
a.setup_method("")
a.test_moodle()
#apprentice=a.get_apprentice()
#print(apprentice)
#fileList=pd.DataFrame()
