# Generated by Selenium IDE
# =============================================================================
# LIbraries
# =============================================================================

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# =============================================================================
# Global varaibles
# =============================================================================
answers=['0','1','2','3','0','1','2','3','0','1','2','3','0','1','2','3','0','1','2','3']

# =============================================================================
# Classes and Functions
# =============================================================================
class test_moodle_quiz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def complete_all_questions(self):
    self.driver.get("http://192.168.1.86/moodle/mod/quiz/view.php?id=2")
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("brownam0")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("87sZL9*2%0&e")
    self.driver.find_element(By.ID, "loginbtn").click()

    #Click re-attempt quiz
    self.driver.find_element_by_class_name('btn-secondary').click()
    
    for i in range(len(answers)):
        print("Answer %s=%s" % (i,answers[i]))

        if (i < len(answers)):            
            this_answer="input[type='radio'][value='{answer}']".format(answer=answers[i])
            self.driver.find_element_by_css_selector(this_answer).click()
            self.driver.find_element_by_css_selector("input[type='submit'][name='next']").click()
        else:
            self.driver.find_element_by_css_selector("input[type='submit'][name='next']").click()
            self.driver.find_element_by_css_selector("button[type='submit'][class='btn btn-secondary']").click()
            #self.driver.find_element_by_css_selector("input[type='submit'][text='Submit all and finish']").click()
            #self.driver.find_element_by_class_name('btn-secondary').click()
    #self.driver.find_element_by_css_selector("button[type='submit'][text='Submit all and finish']").click()
    #self.driver.find_element_by_css_selector("//button[text()='Submit all and finish']").click()
    #self.driver.find_element(By.LinkText("Submit all and finish")).click()
    #self.driver.find_element_by_css_selector("//form//button[text()='Submit all and finish']").click()
    #self.driver.find_element_by_css_selector("input[type='hidden'][name='finishattempt']").click()
    
    #Click Submit
    button=self.driver.find_elements_by_xpath("//*[contains(text(), 'Submit all and finish')]")
    button[0].click()
    
    #Click Final Submit 
    # button=self.driver.find_elements_by_xpath("//*[contains(text(), 'Submit all and finish')]")
    # button[0].click()
    
    time.sleep(1)
    self.driver.find_element_by_css_selector("[value='Submit all and finish']").click()
    
    
    self.driver.find_element_by_xpath("(//a[contains(text(),'Finish review')])").click()
    #self.driver.find_element_by_css_selector("button[type='submit'][class='btn btn-secondary']").click()
        #time.sleep(1)
    
    # #Provide 2s to complete login
    # time.sleep(2)
    
    # self.driver.set_window_size(1354, 3000)
    # #<button type="submit" class="btn btn-secondary" id="single_button5f5ca6656c13214" title="">Re-attempt quiz</button>
    # #self.driver.find_element(By.ID, "single_button5f5ca429728e714").click()
    # self.driver.find_element_by_class_name('btn-secondary').click()
    
    # #self.driver.find_element(By.XPATH("//*[ends-with(@id,'1_answer0')]")).click()
    # #self.driver.find_element(By.XPATH("//input[ends-with(@id,'1_answer0')]")).click()
    # #self.driver.find_element(By.XPATH("//radio[ends-with(@id,'1_answer0')]")).click()
    # #self.driver.find_element(By.XPATH("//radio[contains(@name,'1_answer0')]")).click()
    # self.driver.find_element_by_css_selector("input[type='radio'][value='3']").click()
    # self.driver.find_element_by_css_selector("input[type='submit']").click()
    # self.driver.find_element_by_css_selector("input[type='radio'][value='2']").click()
    # self.driver.find_element_by_css_selector("input[type='submit']").click()
    #self.driver.find_element(By.ID, "single_button5f5c9ef86769314").click()
    # self.driver.find_element(By.ID, "q10:1_answer0").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905535121_30").click()
    # self.driver.find_element(By.ID, "q10:2_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905539705_31").click()
    # self.driver.find_element(By.ID, "q10:3_answer2").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905543028_31").click()
    # self.driver.find_element(By.ID, "q10:4_answer3").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905545897_31").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905548237_115").click()
    # self.driver.find_element(By.ID, "q10:5_answer0").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905548237_31").click()
    # self.driver.find_element(By.ID, "q10:6_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905550857_31").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905553638_115").click()
    # self.driver.find_element(By.ID, "q10:7_answer2").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905553638_31").click()
    # self.driver.find_element(By.ID, "q10:8_answer3").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905557416_31").click()
    # self.driver.find_element(By.ID, "q10:9_answer0").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905559758_31").click()
    # self.driver.find_element(By.ID, "q10:10_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905562287_31").click()
    # self.driver.find_element(By.ID, "q10:11_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905565141_31").click()
    # self.driver.find_element(By.ID, "q10:12_answer2").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905567553_31").click()
    # self.driver.find_element(By.ID, "q10:13_answer3").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905569992_31").click()
    # self.driver.find_element(By.ID, "q10:14_answer0").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905573373_31").click()
    # self.driver.find_element(By.ID, "q10:15_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905576566_31").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905579303_115").click()
    # self.driver.find_element(By.ID, "q10:16_answer2").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905579303_31").click()
    # self.driver.find_element(By.ID, "q10:17_answer3").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905582000_31").click()
    # self.driver.find_element(By.ID, "q10:18_answer0").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905584352_31").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905586910_115").click()
    # self.driver.find_element(By.ID, "q10:19_answer1").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905586910_31").click()
    # self.driver.find_element(By.ID, "q10:20_answer2").click()
    # self.driver.find_element(By.ID, "yui_3_17_2_1_1599905592090_31").click()
    # self.driver.find_element(By.ID, "single_button5f5c9f3c5043416").click()
    # self.driver.find_element(By.ID, "id_yuiconfirmyes-yui_3_17_2_2_1599905596526_8").click()
  
a=test_moodle_quiz()
a.setup_method("")
a.complete_all_questions()