# Generated by Selenium IDE
# =============================================================================
# LIbraries
# =============================================================================

import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

# =============================================================================
# Global varaibles
# =============================================================================
#answers=['0','1','2','3','0','1','2','3','0','1','2','3','0','1','2','3','0','1','2','3']
answers=['0','1','2','3','0','1','2','3','0','1','2','3','0','1','2','3']

# =============================================================================
# Classes and Functions
# =============================================================================
class test_moodle_quiz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def complete_all_questions(self):
    self.driver.get("https://assessment.accelerate-people.co.uk/mod/quiz/view.php?id=7")
    
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("andyb@accelerate-people.co.uk")
  
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("7%xdEuxukblTOW0Z")

    self.driver.find_element(By.ID, "loginbtn").click()

    #Click re-attempt quiz
    self.driver.find_element_by_class_name('btn-secondary').click()
    
    #Becuuse there is a time limit click the start box
    time.sleep(4)
    #self.driver.find_element(By.ID, "moodle-dialogue-yui_3_17_2_1_1605038957469_56-wrap-header-text").click()
    #self.driver.find_element(By.ID, "moodle-dialogue-yui_3_17_2_1_1605039248659_55-wrap-header-text").click()
    self.driver.find_element(By.ID, "id_submitbutton").click()
  
    
    
    
    
    for i in range(len(answers)):
        print("Answer %s=%s" % (i,answers[i]))

        if (i < len(answers)):            
            this_answer="input[type='radio'][value='{answer}']".format(answer=answers[i])
            self.driver.find_element_by_css_selector(this_answer).click()
            self.driver.find_element_by_css_selector("input[type='submit'][name='next']").click()
        else:
            self.driver.find_element_by_css_selector("input[type='submit'][name='next']").click()
            self.driver.find_element_by_css_selector("button[type='submit'][class='btn btn-secondary']").click()
  
    
    #Click Submit
    #button=self.driver.find_elements_by_xpath("//*[contains(text(), 'Submit all and finish')]")
    
    
    #Click Final Submit 
    # button=self.driver.find_elements_by_xpath("//*[contains(text(), 'Submit all and finish')]")
    # button[0].click()
    
    time.sleep(1)
    #<button type="submit" class="btn btn-secondary" id="single_button5faaf7a061a5518" title="">Submit all and finish</button>
    
    #self.driver.find_element_by_css_selector("[title='Submit all and finish']").click()
    self.driver.find_element_by_xpath('//button[text()="Submit all and finish"]').click()
    time.sleep(1)
    
    #<input type="button" class="btn btn-primary" id="id_yuiconfirmyes-yui_3_17_2_3_1605123953847_6" value="Submit all and finish">#
    #<input type="button" class="btn btn-primary" id="id_yuiconfirmyes-yui_3_17_2_2_1605040984860_7" value="Submit all and finish">
    #self.driver.find_element_by_xpath('//button[text()="Submit all and finish"]').click()
    self.driver.find_element_by_css_selector("input[type='button'][class='btn btn-primary']").click()
    #self.driver.find_element_by_xpath('//button[text()="Submit all and finish"]').click()
    #self.driver.find_element_by_xpath('[value="Submit all and finish"]').click()
    
    #self.driver.find_element_by_xpath("(//a[contains(text(),'Finish review')])").click()
    
  
a=test_moodle_quiz()
a.setup_method("")
a.complete_all_questions()