# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestMoodle():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_moodle(self):
    self.driver.get("http://192.168.1.86/moodle/")
    self.driver.set_window_size(1354, 824)
    self.driver.find_element(By.LINK_TEXT, "Log in").click()
    self.driver.find_element(By.ID, "username").click()
    self.driver.find_element(By.ID, "username").send_keys("brownam0")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("87sZL9*2%0&e")
    self.driver.find_element(By.ID, "loginbtn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".multiline").click()
    self.driver.find_element(By.CSS_SELECTOR, "#module-2 .instancename").click()
    self.driver.find_element(By.ID, "single_button5f56296f4582a14").click()
    self.driver.find_element(By.ID, "q5:1_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482230563_30").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482241978_115").click()
    self.driver.find_element(By.ID, "q5:2_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482241978_31").click()
    self.driver.find_element(By.ID, "q5:3_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482245935_31").click()
    self.driver.find_element(By.ID, "q5:4_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482249186_31").click()
    self.driver.find_element(By.ID, "q5:5_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482252438_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482256346_115").click()
    self.driver.find_element(By.ID, "q5:6_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482256346_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482259293_115").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482259293_115").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482259293_115").click()
    self.driver.find_element(By.ID, "q5:7_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482259293_31").click()
    self.driver.find_element(By.ID, "q5:8_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482267825_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482270230_115").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482270230_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482273912_115").click()
    self.driver.find_element(By.ID, "q5:10_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482273912_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482277445_115").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482277445_115").click()
    self.driver.find_element(By.ID, "q5:11_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482277445_31").click()
    self.driver.find_element(By.ID, "q5:12_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482281973_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482284734_115").click()
    self.driver.find_element(By.ID, "q5:13_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482284734_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482287798_115").click()
    self.driver.find_element(By.ID, "q5:14_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482287798_31").click()
    self.driver.find_element(By.ID, "q5:15_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482293129_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482295653_115").click()
    self.driver.find_element(By.ID, "q5:16_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482295653_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482298466_115").click()
    self.driver.find_element(By.ID, "q5:17_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482298466_31").click()
    self.driver.find_element(By.ID, "q5:18_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482302335_31").click()
    self.driver.find_element(By.ID, "q5:19_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482304355_31").click()
    self.driver.find_element(By.ID, "q5:20_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599482308212_31").click()
    self.driver.find_element(By.ID, "single_button5f5629c73196716").click()
    self.driver.find_element(By.ID, "id_yuiconfirmyes-yui_3_17_2_2_1599482311362_8").click()
    self.driver.close()
  
a=TestMoodle()
a.setup_method("")
a.test_moodle()