# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestQuiz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def complete_all_questions(self):
    self.driver.get("http://192.168.1.86/moodle/mod/quiz/attempt.php?attempt=7&cmid=2")
    self.driver.set_window_size(1696, 1026)
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903582839_30").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903594755_30").click()
    self.driver.find_element(By.ID, "q7:1_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903600092_30").click()
    self.driver.find_element(By.ID, "q7:2_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903606115_31").click()
    self.driver.find_element(By.ID, "q7:3_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903609236_31").click()
    self.driver.find_element(By.ID, "q7:4_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903612616_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903614802_115").click()
    self.driver.find_element(By.ID, "q7:5_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903614802_31").click()
    self.driver.find_element(By.ID, "q7:6_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903617906_31").click()
    self.driver.find_element(By.ID, "q7:7_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903620194_31").click()
    self.driver.find_element(By.ID, "q7:8_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903622363_31").click()
    self.driver.find_element(By.ID, "q7:9_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903624783_31").click()
    self.driver.find_element(By.ID, "q7:10_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903627492_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903630381_115").click()
    self.driver.find_element(By.ID, "q7:11_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903630381_31").click()
    self.driver.find_element(By.ID, "q7:12_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903633398_31").click()
    self.driver.find_element(By.ID, "q7:13_answer1").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903636673_31").click()
    self.driver.find_element(By.ID, "q7:14_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903639549_31").click()
    self.driver.find_element(By.ID, "q7:15_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903643106_31").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903645605_115").click()
    self.driver.find_element(By.ID, "q7:16_answer2").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903645605_31").click()
    self.driver.find_element(By.ID, "q7:17_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903649160_31").click()
    self.driver.find_element(By.ID, "q7:18_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903652162_31").click()
    self.driver.find_element(By.ID, "q7:19_answer0").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903654652_31").click()
    self.driver.find_element(By.ID, "q7:20_answer3").click()
    self.driver.find_element(By.ID, "yui_3_17_2_1_1599903658316_31").click()
    self.driver.find_element(By.ID, "single_button5f5c97acf0eeb16").click()
    self.driver.find_element(By.ID, "id_yuiconfirmyes-yui_3_17_2_2_1599903661161_8").click()
  
    

a=TestQuiz()
a.setup_method("")
a.complete_all_questions()