# -*- coding: utf-8 -*-
"""
Created on Fri Aug 28 09:00:32 2020

@author: andy
"""

# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from bs4 import BeautifulSoup
import pandas as pd
import os
import glob
import shutil
import pandas as pd
from pathlib import Path
import re 
import matplotlib.pyplot as plt
import numpy as np
import math
from datetime import datetime

from os import path
from docx import Document



# =============================================================================
# Global varaibles
# =============================================================================
question_statistics=pd.DataFrame()
difficult_threshold={"min":0.3,"max":0.9}

# =============================================================================
# Functions
# =============================================================================
def get_file_path(directory_name,filename):    
    director_path=Path(directory_name)
    full_file_path=director_path / filename
    return full_file_path
    

    
# # =============================================================================
# # Import Data  
# # =============================================================================

# select qa.id,qa.questionid,qa.questionusageid,q.name,qa.questionsummary,qa.rightanswer,qa.responsesummary,qa.timemodified,qas.state,qas.fraction,qas.userid, username, from_unixtime(qa.timemodified)
# from {question_attempts} qa
# join {question} as q 
# on qa.questionid = q.id
# join {question_attempt_steps} as qas
# on qas.questionattemptid=qa.id
# join {user} as u
# on qas.userid=u.id
# where qas.state in ('gradedright','gradedwrong')
# order by qa.id 



attempts_data_filename=get_file_path(r"C:\Users\Andy.JIVEDIVE.000\OneDrive\Download","Typist stats.xlsx")


#dataset=pd.read_excel(data_orginal_file, sheet_name="TestData",skiprows=range(1,1))
type_df=pd.read_excel(attempts_data_filename)

names=type_df.iloc[:,0]
speed=type_df.iloc[:,6]
type_cleansed_df=pd.concat([names, speed], axis=1).reset_index()
type_cleansed_df.rename(columns={type_cleansed_df.columns[1]: "name",type_cleansed_df.columns[2]: "speed"},inplace=True)
type_cleansed_df['speed'].plot.kde()
mean=type_cleansed_df['speed'].mean()
sd=type_cleansed_df['speed'].std()
time_max=mean+(2*sd)
time_min=mean-(2*sd)

print("mean={}")
print("mean={}".format(mean))
print("sd={}".format(sd))

print("min expected speed for 97% of people ={}".format(time_max))
print("max expected speed for 97^ of people ={}".format(time_min))


#attempts_df=attempts_df.sort_values(by=['questionusageid','questionid'])
#attempts_df=attempts_df.rename(columns={'name':'question_name'})
boxplot = type_cleansed_df.boxplot(column=['speed'], by='name')
